DROP TABLE IF EXISTS beer_flavour;
DROP TABLE IF EXISTS flavour;
DROP TABLE IF EXISTS manufacturer;
DROP TABLE IF EXISTS country;
DROP TABLE IF EXISTS beer_type;
DROP TABLE IF EXISTS beer_store;
DROP TABLE IF EXISTS store;
DROP TABLE IF EXISTS rating;
DROP TABLE IF EXISTS app_user_role;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS app_user;
DROP TABLE IF EXISTS beer;
DROP TYPE IF EXISTS price_category;

CREATE TYPE price_category AS ENUM ('cheap', 'mass_produced', 'craft');
CREATE TYPE app_role AS ENUM ('user', 'admin');

CREATE TABLE flavour (
    id BIGINT PRIMARY KEY generated by default as identity,
    name VARCHAR(127) NOT NULL
);

CREATE TABLE manufacturer (
    id BIGINT PRIMARY KEY generated by default as identity,
    name VARCHAR(127) NOT NULL,
    description VARCHAR(511),
    image VARCHAR(511)
);

CREATE TABLE country (
    id BIGINT PRIMARY KEY generated by default as identity,
    name VARCHAR(127) NOT NULL,
    code VARCHAR(3) NOT NULL,
    description VARCHAR(511)
);

CREATE TABLE beer_type (
    id BIGINT PRIMARY KEY generated by default as identity,
    name VARCHAR(127) NOT NULL,
    description VARCHAR(511)
);

CREATE TABLE beer (
    id BIGINT PRIMARY KEY generated by default as identity,
    beer_type_id BIGINT NOT NULL,
    country_id BIGINT NOT NULL,
    manufacturer_id BIGINT NOT NULL,
    name VARCHAR(127) NOT NULL,
    description VARCHAR(511),
    image VARCHAR(511),
    price_category price_category,
    abv REAL NOT NULL,
    bitterness REAL,
    wort_density REAL,
    lower_serve_temperature INT,
    higher_serve_temperature INT,
    nutrition_facts JSONB,
    FOREIGN KEY(beer_type_id) REFERENCES beer_type(id) ON DELETE CASCADE,
    FOREIGN KEY(country_id) REFERENCES country(id) ON DELETE CASCADE,
    FOREIGN KEY(manufacturer_id) REFERENCES manufacturer(id) ON DELETE CASCADE
);

CREATE TABLE beer_flavour (
    id BIGINT PRIMARY KEY generated by default as identity,
    beer_id BIGINT NOT NULL,
    flavour_id BIGINT NOT NULL,
    FOREIGN KEY(beer_id) REFERENCES beer(id) ON DELETE CASCADE,
    FOREIGN KEY(flavour_id) REFERENCES flavour(id) ON DELETE CASCADE
);

CREATE TABLE store (
    id BIGINT PRIMARY KEY generated by default as identity,
    name VARCHAR(127) NOT NULL,
    image VARCHAR(511)
);

CREATE TABLE beer_store (
    id BIGINT PRIMARY KEY generated by default as identity,
    beer_id BIGINT NOT NULL,
    store_id BIGINT NOT NULL,
    beer_link VARCHAR(511) NOT NULL,
    FOREIGN KEY(beer_id) REFERENCES beer(id) ON DELETE CASCADE,
    FOREIGN KEY(store_id) REFERENCES store(id) ON DELETE CASCADE
);

CREATE TABLE app_user (
    id BIGINT PRIMARY KEY generated by default as identity,
    email VARCHAR(127) UNIQUE NOT NULL,
    password VARCHAR(127) NOT NULL,
    username VARCHAR(63) UNIQUE
);

CREATE TABLE role (
    id BIGINT PRIMARY KEY generated by default as identity,
    name app_role
);

CREATE TABLE app_user_role (
    id BIGINT PRIMARY KEY generated by default as identity,
    app_user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    FOREIGN KEY(app_user_id) REFERENCES app_user(id) ON DELETE CASCADE,
    FOREIGN KEY(role_id) REFERENCES role(id) ON DELETE CASCADE
);

CREATE TABLE rating (
    id BIGINT PRIMARY KEY generated by default as identity,
    app_user_id BIGINT NOT NULL,
    beer_id BIGINT NOT NULL,
    rating REAL NOT NULL,
    comment VARCHAR(511),
    FOREIGN KEY(app_user_id) REFERENCES app_user(id) ON DELETE CASCADE,
    FOREIGN KEY(beer_id) REFERENCES beer(id) ON DELETE CASCADE
);